openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response
          headers:
            X-Rate-Limit:
              schema:
                type: integer
              description: Calls per hour allowed by the user
          content:
            text/plain:
              schema:
                type: string
              example: "Hello, World!"