openapi: 3.0.0
info:
  description: A sample API to illustrate OpenAPI concepts
  title: Sample API
  version: 1.0.0
servers:
- url: /
paths:
  /list:
    get:
      description: Returns a list of stuff
      operationId: listGET
      responses:
        "200":
          content:
            text/plain:
              example: "Hello, World!"
              schema:
                type: string
          description: Successful response
          headers:
            X-Rate-Limit:
              description: Calls per hour allowed by the user
              explode: false
              schema:
                type: integer
              style: simple
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas: {}
